[package]
name = "magic_eye"
version = "0.9.0"
description = "A Tauri App"
authors = ["Thomas Toulouse"]
license = "MIT"
repository = "https://github.com/Sir-Thom/Magic-eye"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html




[build-dependencies]
tauri-build = { version = "^1.5", features = [] }

[dependencies]
tauri = { version = "^1.5.3", features = [ "window-minimize", "window-set-size", "window-set-focus", "window-start-dragging", "window-unminimize", "window-set-resizable", "window-set-title", "window-set-icon", "window-set-decorations", "window-set-cursor-icon", "window-maximize", "window-unmaximize", "window-set-cursor-grab", "window-show", "window-close", "window-set-fullscreen",
    "shell-open",
    "fs-all",
    "http-all",
    "protocol-all",
    "path-all",
    "dialog-all",
] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
axum = "0.7.2"
tokio = { version = "1.35.0", features = ["full"] }
tower-http = { version = "0.5.0", features = ["fs", "cors"] }
reqwest = "^0.11.20"
open = "5.0.0"
log = "0.4.20"
tauri-plugin-log = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
panic = "abort" # Strip expensive panic clean-up logic
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true # Enables link to optimizations
opt-level = "s" # Optimize for binary size
strip = true # Remove debug symbols
