[package]
name = "magic_eye"
version = "0.0.1"
description = "A Tauri App"
authors = ["Thomas Toulouse"]
license = "MIT"
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[patch.crates-io]

[build-dependencies]
tauri-build = { version = "^1.4", features = [] }

[dependencies]
tauri = { version = "^1.4.1", features = [
    "shell-open",
    "protocol-all",
    "window-all",
    "path-all",
    "dialog-all",
    "http-all",
    "devtools",
] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
#gstreamer-video = "0.20.3"
tokio = { version = "^1", features = ["full"] }
tauri-plugin-localhost = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
port-selector = "0.1.6"

#gstreamer = "0.20.3"
#gstreamer-app = "0.20.0"
#gstreamer-player = "^0.20.0"
open = "5.0.0"

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
[profile.release.package.wry]
debug = true
debug-assertions = true
