#!/bin/sh
echo "installing MagicEye..."
chmod +x MagicEye.desktop
cd MagicEye
chmod +x *.py
cd ..
sudo  cp -a MagicEye/.  /usr/bin
cp -a MagicEye/  ~/.local/bin
cp MagicEye.desktop ~/.local/share/applications
echo  "Do you want Camip on your desktop? [y/n]: "
read
         if [[ $REPLY == "y" || $REPLY ==  "Y"  || $REPLY == "yes" ]]; then
                 cp MagicEye.desktop ~/Desktop
                 alias magiceye='python /usr/bin/MagicEye.py' >> ~/.bashrc
                 echo "installation completed"  
                 break
         fi
         if [[  $REPLY == "n" || $REPLY == "N" || $REPLY == "no" ]];then
                alias magiceye='python /usr/bin/MagicEye.py' >> ~/.bashrc
                echo "installation completed"  
                exit
         fi
        if [[ $REPLY != "y" || $REPLY != "Y" || $REPLY != "yes" || $REPLY != "n" || $REPLY != "N" || $REPLY == "no" ]];then
                echo -e -n "\e[0;31m"Error:Invalid input.  " \e[m""Do you want Magic Eye on your desktop? [y/n]"
                read 
                fi
