name: Node.js CI

on:
  push:
    branches: ["Rework-Tauri"]
  pull_request:
    branches: ["Rework-Tauri"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x,20.x,21.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install -f
      - run: npm run format

  unittest:
    runs-on: ubuntu-latest

    needs: build  # Ensure that the 'build' job completes before starting this job

    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install -f
      - run: npm run test  # Replace with the actual command to run your tests
